Repository jowc/africa-localities, pull requests merged in 2024-12, with the labels that each got.

#1 Setup
  nodemon.json
  package-lock.json
  package.json
  src/data-access/models/localities.model.ts
  src/data-access/services/localities.service.ts
  src/data-access/store/localities.store.ts
  src/index.ts
  src/utils/localities.utils.ts
  src/utils/reponse-text.utils.ts
  tsconfig.json
Labels: enhancement

#2 added documentation files
  CODE_OF_CONDUCT.md
  CONTRIBUTION.md
  README.md
  package.json
Labels: documentation

#3 added how to add or see localities to read me
  README.md
Labels: documentation

#4 Feature/locality alias
  README.md
  src/data-access/models/localities.model.ts
  src/data-access/store/localities.store.ts
Labels: enhancement

#5 Documentation/how to
  README.md
  src/data-access/store/localities.store.ts
Labels: documentation

#6 sort localities alphabetically
  src/data-access/services/localities.service.ts
Labels: enhancement

#7 added prettier and linting
  .prettierrc
  src/data-access/models/localities.model.ts
  src/data-access/services/localities.service.ts
  src/data-access/store/localities.store.ts
  src/index.ts
  src/utils/localities.utils.ts
  src/utils/reponse-text.utils.ts
Labels: enhancement

#8 New files from Fly.io Launch
  .dockerignore
  Dockerfile
  fly.toml
Labels: third party

#11 Documentation/how to
  CONTRIBUTION.md
  README.md
  src/data-access/models/localities.model.ts
  src/data-access/services/localities.service.ts
  src/data-access/store/localities.store.ts
Labels: documentation

#12 updated readme
  README.md
Labels: documentation

#16 Added Cross River State data to Nigeria
  src/data-access/store/localities.store.ts
Labels: enhancement
